export const COMING_SOON_ASSETS = {
  hero: "/images/coming-soon/hero-characters.png",
  logo: "/images/coming-soon/marvel-run-logo.png",
  motif: "/images/coming-soon/decor/info-motif.svg",
  motifMobile: "/images/coming-soon/decor/bg_moblie.svg",
  host: "/images/coming-soon/hosted.png",
  organizer: "/images/coming-soon/organizer.png",
} as const;

export const MAIN_ASSETS = {
  logo: "/images/main/logo.svg",
  headerLogo: "/images/main/header-logo.svg",
  footerLogo: "/images/main/ft_logo.svg",
  loadingLogo: "/images/main/loading-logo.png",
  sideBanner: "/images/main/sidebanner.svg",
  footerHost: "/images/main/footer/hosted.png",
  footerOrganizer: "/images/main/footer/organizer.png",
  introMarvel: "/images/main/intro-marvel.svg",
  introRun: "/images/main/intro-run.svg",
  introKorea: "/images/main/intro-korea.svg",
  introCyclops: "/images/main/intro/cyclops.png",
  introThing: "/images/main/intro/thing.png",
  introDoom: "/images/main/intro/doom.png",
  introThor: "/images/main/intro/thor.png",
  introFalcon: "/images/main/intro/falcon.png",
  introPrevCyclops: "/images/main/intro/panel-cyclops.png",
  introPrevThing: "/images/main/intro/panel-thing.png",
  introPrevThor: "/images/main/intro/panel-thor.png",
  introPrevPanther: "/images/main/intro/panel-panther.png",
  introPrevDoom: "/images/main/intro/panel-doom.png",
  course2_3k: "/images/main/guide/course-2.3k.svg",
  course5k: "/images/main/guide/course-5k.svg",
  course10k: "/images/main/guide/course-10k.svg",
  medal2_3kTurn: "/images/main/guide/medal-2.3k-turn.svg",
  medal2_3kBack: "/images/main/guide/medal-2.3k-back.svg",
  medal5kTurn: "/images/main/guide/medal-5k-turn.svg",
  medal5kBack: "/images/main/guide/medal-5k-back.svg",
  medal10kTurn: "/images/main/guide/medal-10k-turn.svg",
  medal10kBack: "/images/main/guide/medal-10k-back.svg",
  medal10k3d: "/models/main/guide/medal-10k.glb",
  medal5k3d: "/models/main/guide/medal-5k.glb",
  medal2_3k3d: "/models/main/guide/medal-2.3k.glb",
  kitBib: "/images/main/guide/kit-bib.svg",
  venueThor: "/images/main/venue/2.3k-thor.png",
  venueCyclops: "/images/main/venue/5k-cyclops.png",
  venueDoom: "/images/main/venue/10k-doom.png",
  virtualBlack: "/images/virtual/black.svg",
  virtualThor: "/images/virtual/thor.svg",
  virtualDom: "/images/virtual/dom.svg",
} as const;
