export const EVENT = {
  title: "MARVEL RUN 2026 KOREA",
  kicker: "OFFICIAL MARVEL EVENT",
  tagline: "ASSEMBLE. RUN.",
  lead: "히어로가 되는 가장 빠른 길",
  openNoticeDate: "2026. 09. 22. 화요일",
  openNoticeTime: "오후 2시",
  openNoticeAction: "접수 OPEN",
  dateShort: "2026.10.31 SAT",
  dateLong: "2026년 10월 31일 토요일",
  venue: "인제스피디움",
  venueEn: "INJE SPEEDIUM",
  venueAddress: "강원 인제군 기린면 상하답로 130 인제스피디움",
  mapUrl: "https://map.naver.com/p/search/%EC%9D%B8%EC%A0%9C%EC%8A%A4%ED%94%BC%EB%94%94%EC%9B%80",
  info: [
    {
      label: "대회일시",
      value: "2026년 10월 31일 토요일",
    },
    {
      label: "대회장소",
      value: "인제스피디움",
      note: "강원 인제군 기린면 상하답로 130 인제스피디움",
    },
    {
      label: "접수일정",
      value: "2026년 9월 22일 화요일 오후 2시",
    },
  ],
  stats: [
    { value: "42.195", unit: "KM", label: "ENDGAME" },
    { value: "10.31", unit: "SAT", label: "RACE DAY" },
    { value: "4", unit: "", label: "COURSES" },
    { value: "INJE", unit: "", label: "SPEEDIUM" },
  ],
  courses: [
    {
      id: "5k",
      distance: "5K",
      code: "FIRST STRIKE",
      tone: "red",
      timeLimit: "1시간",
      fee: "50,000원",
      start: "09:00",
      desc: "첫 미션. 히어로의 각성.",
    },
    {
      id: "10k",
      distance: "10K",
      code: "ASSEMBLE",
      tone: "cyan",
      timeLimit: "1시간 30분",
      fee: "60,000원",
      start: "08:30",
      desc: "팀을 모아 거리를 장악한다.",
    },
    {
      id: "half",
      distance: "21.1K",
      code: "LEGEND",
      tone: "gold",
      timeLimit: "3시간",
      fee: "80,000원",
      start: "08:00",
      desc: "전설의 절반. 망치를 들어라.",
    },
    {
      id: "full",
      distance: "42.195K",
      code: "ENDGAME",
      tone: "violet",
      timeLimit: "6시간",
      fee: "100,000원",
      start: "07:30",
      desc: "최후의 미션. 모든 것을 걸어라.",
    },
  ],
  timeline: [
    { time: "06:00", title: "집결 · 웨이스트백 보관" },
    { time: "07:00", title: "워밍업 · 히어로 포토존" },
    { time: "07:30", title: "풀코스 스타트" },
    { time: "08:00", title: "하프 스타트" },
    { time: "08:30", title: "10K 스타트" },
    { time: "09:00", title: "5K 스타트" },
    { time: "15:00", title: "피니시 클로징" },
  ],
  kit: [
    "공식 티셔츠",
    "배번호 · 타이밍칩",
    "피니셔 메달",
    "웨이스트백",
  ],
  notices: [
    {
      id: "3",
      date: "2026.09.10",
      tag: "NOTICE",
      title: "MARVEL RUN 2026 KOREA 공식 홈페이지 오픈",
      pinned: true,
      body: "대회안내, 코스, 오시는길을 공식 홈페이지에서 확인할 수 있습니다. 참가 접수는 9월 22일 오후 2시에 시작됩니다.",
    },
    {
      id: "2",
      date: "2026.09.10",
      tag: "RACE",
      title: "코스별 스타트 타임 안내",
      pinned: false,
      body: "풀 07:30, 하프 08:00, 10K 08:30, 5K 09:00. 스타트 30분 전까지 집결을 완료해 주세요.",
    },
    {
      id: "1",
      date: "2026.09.10",
      tag: "ENTRY",
      title: "참가 접수 9월 22일 오후 2시 오픈",
      pinned: false,
      body: "코스 선택 후 참가자 정보를 입력하면 주문번호가 발급됩니다. 접수 내역은 신청조회에서 확인합니다.",
    },
  ],
  sponsors: [
    { role: "주최", name: "ONEUNIVERSE" },
    { role: "주관", name: "FLUX SONIC" },
  ],
  copyright: "©2026 MARVEL",
} as const;
