import { MAIN_ASSETS } from "./assets";

export const EVENT = {
  title: "MARVEL RUN 2026 KOREA",
  tagline: "ASSEMBLE. RUN.",
  lead: "히어로가 되는 가장 빠른 길",
  openNoticeDate: "2026. 09. 22. 화요일",
  openNoticeTime: "오후 2시",
  openNoticeAction: "접수 OPEN",
  /* 접수 오픈 — 카운트다운 */
  openAt: "2026-09-22T14:00:00+09:00",
  /* 홈 팝업 — 끄려면 enabled: false. image에 경로 넣으면 본문에 표시 */
  popup: {
    enabled: true,
    id: "home-open",
    title: "안내",
    image: "",
  },
  dateShort: "2026.10.31 SAT",
  dateLong: "2026년 10월 31일 토요일",
  /* 대회일 YYYYMMDD — 만 나이 컷 */
  raceYmd: "20261031",
  venue: "인제스피디움",
  venueEn: "INJE SPEEDIUM",
  venueAddress: "강원 인제군 기린면 상하답로 130 인제스피디움",
  venueLat: 38.00139,
  venueLng: 128.29194,
  mapUrl: "https://map.kakao.com/link/map/인제스피디움,38.00139,128.29194",
  venueAccess: [
    {
      title: "자가용",
      items: [
        {
          badge: "고속",
          text: "서울양양고속도로 인제IC | 기린면 방면 약 20분",
        },
        {
          badge: "국도",
          text: "44번 국도 기린면 | 상하답로 진입",
        },
      ],
    },
    {
      title: "버스",
      note: "인제시외버스터미널 하차",
      items: [
        {
          badge: "시외",
          text: "동서울 · 춘천 → 인제",
        },
        {
          badge: "택시",
          text: "터미널에서 약 25분",
        },
      ],
    },
  ],
  info: [
    {
      label: "대회일시",
      value: "2026년 10월 31일 토요일",
    },
    {
      label: "대회장소",
      value: "인제스피디움",
      note: "강원 인제군 기린면 상하답로 130 인제스피디움",
    },
    {
      label: "접수일정",
      value: "2026년 9월 22일 화요일 오후 2시",
    },
  ],
  stats: [
    { value: "3", unit: "", label: "COURSES" },
    { value: "10.31", unit: "SAT", label: "RACE DAY" },
    { value: "10 / 5 / 2.3", unit: "Km", label: "MISSIONS" },
    { value: "INJE", unit: "", label: "SPEEDIUM" },
  ],
  courses: [
    {
      id: "10k",
      distance: "10 Km",
      code: "ASSEMBLE",
      tone: "cyan",
      fee: "70,000원",
      start: "13:30",
      desc: "한계를 넘어 서킷을 완주하는 히어로 레이스",
      map: MAIN_ASSETS.course10k,
      figure: MAIN_ASSETS.venueDoom,
    },
    {
      id: "5k",
      distance: "5 Km",
      code: "FIRST STRIKE",
      tone: "red",
      fee: "70,000원",
      childFee: "40,000원",
      start: "14:00",
      desc: "스피드와 재미를 함께 즐기는 액션 레이스",
      map: MAIN_ASSETS.course5k,
      figure: MAIN_ASSETS.venueCyclops,
    },
    {
      id: "2.3k",
      distance: "2.3 Km",
      code: "ORIGIN",
      tone: "gold",
      fee: "55,000원",
      childFee: "40,000원",
      start: "14:30",
      desc: "어린이 히어로와 함께 달리는 패밀리 레이스",
      map: MAIN_ASSETS.course2_3k,
      figure: MAIN_ASSETS.venueThor,
    },
  ],
  timeline: [
    {
      from: "11:00",
      to: "",
      rt: "–",
      program: "MARVEL RUN 2026 오픈",
      note: "F&B, 컨텐츠 존 운영",
      mark: "gate",
    },
    {
      from: "13:00",
      to: "13:30",
      rt: "30′",
      program: "준비운동 및 무대행사 : (10 Km)",
      note: "",
    },
    {
      from: "13:30",
      to: "",
      rt: "–",
      program: "10 Km 러닝 시작",
      note: "",
      mark: "10k",
    },
    {
      from: "13:30",
      to: "14:00",
      rt: "30′",
      program: "준비운동 및 무대행사 : (5 Km)",
      note: "",
    },
    {
      from: "14:00",
      to: "",
      rt: "–",
      program: "5 Km 러닝 시작",
      note: "",
      mark: "5k",
    },
    {
      from: "14:00",
      to: "14:30",
      rt: "30′",
      program: "준비운동 및 무대행사 : (2.3 Km)",
      note: "",
    },
    {
      from: "14:30",
      to: "",
      rt: "–",
      program: "2.3 Km 러닝 시작",
      note: "",
      mark: "2.3k",
    },
    {
      from: "",
      to: "16:00",
      rt: "–",
      program: "러닝 행사 종료",
      note: "서킷 폐장",
    },
    {
      from: "16:00",
      to: "18:00",
      rt: "–",
      program: "시상식 및 무대 행사",
      note: "상세 컨텐츠 TBD",
    },
    {
      from: "",
      to: "19:00",
      rt: "–",
      program: "MARVEL RUN 2026 종료",
      note: "",
      mark: "gate",
    },
  ],
  kit: [
    "공식 티셔츠",
    "배번호 · 타이밍칩",
    "피니셔 메달",
    "웨이스트백",
  ],
  notices: [
    {
      id: "3",
      date: "2026.09.10",
      tag: "필독",
      title: "MARVEL RUN 2026 KOREA 공식 홈페이지 오픈",
      pinned: true,
      body: "대회안내, 코스, 오시는길을 공식 홈페이지에서 확인할 수 있습니다. 참가 접수는 9월 22일 오후 2시에 시작됩니다.",
    },
    {
      id: "2",
      date: "2026.09.10",
      tag: "이벤트",
      title: "코스별 스타트 타임 안내",
      pinned: false,
      body: "10 Km 13:30, 5 Km 14:00, 2.3 Km 14:30. 스타트 30분 전까지 집결을 완료해 주세요.",
    },
    {
      id: "1",
      date: "2026.09.10",
      tag: "일반",
      title: "참가 접수 9월 22일 오후 2시 오픈",
      pinned: false,
      body: "코스 선택 후 참가자 정보를 입력하면 주문번호가 발급됩니다. 접수 내역은 신청조회에서 확인합니다.",
    },
  ],
  sponsors: [
    { role: "주최", name: "ONEUNIVERSE STUDIO" },
    { role: "주관", name: "FLUX SONIC" },
  ],
  copyright: "©2026 MARVEL",
} as const;
